<?php

namespace App\Http\Controllers\Api;

use App\Concerns\GuardsSensitiveExports;
use App\Http\Controllers\Controller;
use App\Models\AuditLog;
use App\Models\ExportRequest;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Symfony\Component\HttpFoundation\StreamedResponse;

class AuditLogController extends Controller
{
    use GuardsSensitiveExports;

    public function index(Request $request)
    {
        $this->authorizeAuditAccess();
        $user = Auth::user();

        $query = AuditLog::with('user');
        $this->applyAuditUserScope($query, $user);

        // Filters
        if ($module = $request->get('module')) {
            if ($module !== 'all') {
                $query->where('module', $module);
            }
        }

        if ($userId = $request->get('user_id')) {
            if ($userId !== 'all') {
                $query->where('user_id', $userId);
            }
        }

        if ($from = $request->get('date_from')) {
            $query->whereDate('logged_at', '>=', Carbon::parse($from)->toDateString());
        }

        if ($to = $request->get('date_to')) {
            $query->whereDate('logged_at', '<=', Carbon::parse($to)->toDateString());
        }

        if ($q = $request->get('q')) {
            $query->where(function ($qBuilder) use ($q) {
                $qBuilder->where('action', 'like', "%$q%")
                    ->orWhere('module', 'like', "%$q%")
                    ->orWhere('ip_address', 'like', "%$q%")
                    ->orWhere('meta', 'like', "%$q%");
            });
        }

        $perPage = (int) $request->get('per_page', 20);

        $logs = $query->orderByDesc('logged_at')->paginate($perPage);

        // Shape data slightly for frontend convenience
        $logs->getCollection()->transform(function ($log) {
            return [
                'id'         => $log->id,
                'user_name'  => optional($log->user)->name,
                'action'     => $log->action,
                'module'     => $log->module,
                'ip_address' => $log->ip_address,
                'logged_at'  => optional($log->logged_at)->toDateTimeString(),
            ];
        });

        return $logs;
    }

    public function show(AuditLog $auditLog)
    {
        $this->authorizeAuditAccess();
        $this->authorizeAuditBank($auditLog);

        $auditLog->load('user');

        return [
            'id'         => $auditLog->id,
            'user_name'  => optional($auditLog->user)->name,
            'action'     => $auditLog->action,
            'module'     => $auditLog->module,
            'ip_address' => $auditLog->ip_address,
            'meta'       => $auditLog->meta,
            'logged_at'  => optional($auditLog->logged_at)->toDateTimeString(),
        ];
    }

    public function export(Request $request): StreamedResponse
    {
        $this->authorizeAuditAccess();
        $user = Auth::user();

        $exportRequest = $this->requireExportAuthorization($request, 'audit_logs', 'CSV export of Audit Trail logs');
        if ($exportRequest instanceof \Illuminate\Http\JsonResponse) {
            return $exportRequest;
        }

        $fileName = 'audit_logs_' . date('Y-m-d_H-i-s') . '.csv';

        $headers = [
            'Content-Type'        => 'text/csv; charset=UTF-8',
            'Content-Disposition' => 'attachment; filename="' . $fileName . '"',
            'Pragma'              => 'no-cache',
            'Cache-Control'       => 'must-revalidate, post-check=0, pre-check=0',
            'Expires'             => '0',
        ];

        $callback = function () use ($request, $user, $exportRequest, $fileName) {
            $handle = fopen('php://output', 'w');

            // Metadata banner
            fputcsv($handle, ['Export Type', 'System Audit Log']);
            fputcsv($handle, ['Generated At', date('Y-m-d H:i:s')]);
            fputcsv($handle, ['Generated By', $user->name . ' (' . $user->email . ')']);
            fputcsv($handle, ['User Role', $user->role]);
            fputcsv($handle, []);

            // Header row
            fputcsv($handle, [
                'ID',
                'User',
                'Bank ID',
                'Module',
                'Action',
                'IP Address',
                'Logged At',
            ]);

            $query = AuditLog::with('user');
            $this->applyAuditUserScope($query, $user);

            // same filters as index()
            if ($module = $request->get('module')) {
                if ($module !== 'all') {
                    $query->where('module', $module);
                }
            }

            if ($userId = $request->get('user_id')) {
                if ($userId !== 'all') {
                    $query->where('user_id', $userId);
                }
            }

            if ($from = $request->get('date_from')) {
                $query->whereDate('logged_at', '>=', Carbon::parse($from)->toDateString());
            }

            if ($to = $request->get('date_to')) {
                $query->whereDate('logged_at', '<=', Carbon::parse($to)->toDateString());
            }

            if ($q = $request->get('q')) {
                $query->where(function ($qBuilder) use ($q) {
                    $qBuilder->where('action', 'like', "%$q%")
                        ->orWhere('module', 'like', "%$q%")
                        ->orWhere('ip_address', 'like', "%$q%")
                        ->orWhere('meta', 'like', "%$q%");
                });
            }

            $query->orderByDesc('logged_at')->chunk(200, function ($logs) use ($handle) {
                foreach ($logs as $log) {
                    fputcsv($handle, [
                        $log->id,
                        optional($log->user)->name,
                        $log->bank_id,
                        $log->module,
                        $log->action,
                        $log->ip_address,
                        optional($log->logged_at)->toDateTimeString(),
                    ]);
                }
            });

            fclose($handle);
        };

        $this->markSensitiveExportCompleted($exportRequest, $fileName);

        return response()->stream($callback, 200, $headers);
    }

    protected function applyAuditUserScope($query, \App\Models\User $user): void
    {
        // 1. Bank scoping
        if (!$user->canAccessAllBanks() && !empty($user->resolvedBankIds())) {
            $bankIds = $user->resolvedBankIds();
            $query->where(function ($q) use ($bankIds) {
                $q->whereIn('bank_id', $bankIds)
                  ->orWhereNull('bank_id');
            });
        }

        // 2. User scoping
        if (!$user->canViewAuditLogsAllUsers()) {
            $query->where('user_id', $user->id);
        }
    }

    protected function authorizeAuditAccess(): void
    {
        $user = Auth::user();

        if (!$user || !$user->canViewAuditLogs()) {
            abort(403, 'You are not allowed to access audit logs.');
        }
    }

    protected function authorizeAuditBank(AuditLog $auditLog): void
    {
        $user = Auth::user();

        if (!$user) {
            abort(403);
        }

        if (!$user->canAccessAllBanks() && !empty($user->resolvedBankIds())) {
            if ($auditLog->bank_id !== null && !in_array((int) $auditLog->bank_id, $user->resolvedBankIds(), true)) {
                abort(403, 'You do not have permission to access this log.');
            }
        }

        if (!$user->canViewAuditLogsAllUsers()) {
            if ((int) $auditLog->user_id !== (int) $user->id) {
                abort(403, 'You do not have permission to view audit logs for other users.');
            }
        }
    }
}
